_target_: src.model.EDMPrecond
hparams:
  arch:
    residual_layers: 15 #
    residual_channels: 64
    pos_emb_dim: 512
    bsft_channels: 64
    use_convnext: False

  audio:
    filter_length: 1024
    hop_length: 256
    win_length: 1024
    sampling_rate: 48000
    sr_min: 6000
    sr_max: 48000
    length: 32768 #32*1024 ~ 1sec


  logsnr:
    logsnr_min: -20.0
    logsnr_max: 20.0

  dpm:
    max_step: 1000
    pos_emb_scale: 50000
    pos_emb_channels: 128 
    infer_step: 8
    infer_schedule: "torch.tensor([-2.6, -0.8, 2.0, 6.4, 9.8, 12.9, 14.4, 17.2])"
